server:
  port: ${PORT:8761}

spring:
    profiles.active: dev

logging:
  level:
    root: WARN
    com.elderbyte: INFO

eureka:
  instance:
    healthCheckUrlPath: /health
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl.defaultZone: http://localhost:${server.port}/eureka/
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0

endpoints:
  enabled: false
  health:
    enabled: true

