server:
  port: ${PORT:8761}

spring.application.name: "eureka-server"

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      enableSelfPreservation: true
      waitTimeInMsWhenSyncEmpty: 0

logging:
    level:
        root: WARN
        com.elderbyte: INFO